import {
  ArrowUp,
  BookOpen,
  Briefcase,
  Check,
  ChevronDown,
  Circle,
  Clock,
  Cloud,
  Code,
  CodeXml,
  Copy,
  Database,
  ExternalLink,
  FileText,
  GitBranch,
  GitCommitHorizontal,
  Globe,
  Heart,
  History,
  Info,
  Layers,
  Lightbulb,
  Link,
  Mail,
  Map as MapIcon,
  Menu,
  MessageSquare,
  NotebookPen,
  Package,
  PanelsTopLeft,
  Pencil,
  RefreshCw,
  Rss,
  Server,
  Shield,
  Star,
  Tag,
  TriangleAlert,
  Users,
  Wrench,
} from "@lucide/astro";

// Explicit registry: every icon must be imported above and listed here so
// unused Lucide icons are tree-shaken out of the bundle.
export const icons = {
  "arrow-up": ArrowUp,
  book: BookOpen,
  bulb: Lightbulb,
  briefcase: Briefcase,
  check: Check,
  "chevron-down": ChevronDown,
  circle: Circle,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  "code-xml": CodeXml,
  copy: Copy,
  database: Database,
  document: FileText,
  "external-link": ExternalLink,
  "git-branch": GitBranch,
  "git-commit": GitCommitHorizontal,
  globe: Globe,
  heart: Heart,
  history: History,
  info: Info,
  layers: Layers,
  layout: PanelsTopLeft,
  link: Link,
  mail: Mail,
  map: MapIcon,
  menu: Menu,
  "message-square": MessageSquare,
  notebook: NotebookPen,
  package: Package,
  pencil: Pencil,
  refresh: RefreshCw,
  rss: Rss,
  server: Server,
  shield: Shield,
  star: Star,
  tag: Tag,
  "triangle-alert": TriangleAlert,
  tool: Wrench,
  users: Users,
} as const;

export type IconName = keyof typeof icons;
export const iconNames = Object.keys(icons) as IconName[];
