import {
  BookOpen,
  Briefcase,
  Check,
  Circle,
  Clock,
  Cloud,
  Code,
  CodeXml,
  Database,
  ExternalLink,
  FileText,
  GitBranch,
  Globe,
  Heart,
  Info,
  Lightbulb,
  Mail,
  Map as MapIcon,
  Menu,
  PanelsTopLeft,
  RefreshCw,
  Rss,
  Server,
  Shield,
  Star,
  Tag,
  Users,
  Wrench,
} from "@lucide/astro";

// Explicit registry: every icon must be imported above and listed here so
// unused Lucide icons are tree-shaken out of the bundle.
export const icons = {
  book: BookOpen,
  bulb: Lightbulb,
  briefcase: Briefcase,
  check: Check,
  circle: Circle,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  "code-xml": CodeXml,
  database: Database,
  document: FileText,
  "external-link": ExternalLink,
  "git-branch": GitBranch,
  globe: Globe,
  heart: Heart,
  info: Info,
  layout: PanelsTopLeft,
  mail: Mail,
  map: MapIcon,
  menu: Menu,
  refresh: RefreshCw,
  rss: Rss,
  server: Server,
  shield: Shield,
  star: Star,
  tag: Tag,
  tool: Wrench,
  users: Users,
} as const;

export type IconName = keyof typeof icons;
export const iconNames = Object.keys(icons) as IconName[];
